### ISSUE TITLE
Can't set headers after they are sent (NodeJS/FS API)

### ISSUE THREAD

**Issue by marcelherd** [INT-WAW/Slides#11]
Versuche gerade die Funktionalität für den Toggle Button zu implementieren.
Es sollen alle Statuses (wtf?) ausgelesen werden, ggf. workload des angegebenen Status aktualisiert werden und dann die Datei neu geschrieben werden.
Funktioniert alles soweit auch:

```javascript
	router.post('/status/', (req, res) => {
		fs.readFile('./database/status.json', 'utf-8', (error, data) => {
			let statuses = JSON.parse(data);
			for (let status of statuses) {
				if (status.id == req.body.id) {
					status.workload = (req.body.status ? 1 : 0);
					fs.writeFile('./database/status.json', JSON.stringify(statuses), (err) => {
						res.json({ message: 'OK' });
					});
				}
			}
			res.json({ message: 'NOT OK' });
		});
	});
```

Aber leider stürzt Node dann ab ¯\\_(ツ)_/¯

```
_http_outgoing.js:356
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (D:\Workspaces\Boilerplate\CNC\Server\node_modules\express\lib\response.js:719:10)
    at ServerResponse.send (D:\Workspaces\Boilerplate\CNC\Server\node_modules\express\lib\response.js:164:12)
    at ServerResponse.json (D:\Workspaces\Boilerplate\CNC\Server\node_modules\express\lib\response.js:250:15)
    at fs.writeFile (D:\Workspaces\Boilerplate\CNC\Server\api.js:24:11)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

![](http://i.imgur.com/VAvqeoe.jpg)

**Comment by marcelherd** [comment]
Ist das ok hier writeFileSync zu benutzen?:

```
router.post('/status/', (req, res) => {
		fs.readFile('./database/status.json', 'utf-8', (error, data) => {
			let statuses = JSON.parse(data);
			for (let status of statuses) {
				if (status.id == req.body.id) {
					status.workload = (req.body.status ? 1 : 0);
					fs.writeFileSync('./database/status.json', JSON.stringify(statuses));
					res.json({ message: 'OK' });
					return;
				}
			}
			res.json({ message: 'NOT OK' });
		});
	});
```

**Comment by cookiengineer** [comment]
Immer daran denken, dass `res.json()` nicht mehrmals gecalled werden darf. Wenn du asynchron die daten speichern willst und den ueberblick verlierst, mach dir ne hilfsmethode wie `_store_status()` oder so, die das dann halt asynchron macht ohne den flow zu blockieren.

**Comment by cookiengineer** [comment]
Noch etwas wichtiges: In einem loop niemals HTTP responses schicken. Der Ansatz mit for (let id in status...) wuerde ich negativ bewerten, da darin ein response geschickt wird.

Dafuer habt ihr Array.prototype.find kennengelernt :)
